# Generated by Django 3.0.7 on 2021-06-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_verify_sign_sha2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='currency_rate',
        ),
    ]
