# Generated by Django 3.0.7 on 2021-06-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orders_currency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='card_brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='risk_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='risk_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tran_id',
            field=models.CharField(max_length=50),
        ),
    ]
